version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080 # replace with OpenFaaS gateway address
functions:
  template-python:
    lang: python3-http
    handler: ../functions/template-python
    image: template-python:latest

  node14-fun:
    lang: node14
    handler: ../functions/template-node
    image: node14-fun:latest
